{
  "packages": [
    "apps/*",
    "packages/*"
  ],
  "catalog": {
    "@tailwindcss/vite": "^4.1.18",
    "@tanstack/eslint-config": "^0.3.0",
    "@tanstack/react-devtools": "^0.2.2",
    "@tanstack/react-router": "^1.144.0",
    "@tanstack/react-router-devtools": "^1.144.0",
    "@tanstack/react-router-ssr-query": "^1.144.0",
    "@tanstack/react-start": "^1.145.1",
    "@tanstack/router-plugin": "^1.145.1",
    "@testing-library/dom": "^10.4.1",
    "@testing-library/react": "^16.3.1",
    "@types/react": "^19.2.7",
    "@types/react-dom": "^19.2.3",
    "@vitejs/plugin-react": "^4.3.4",
    "jsdom": "^26.0.0",
    "react": "^19.2.3",
    "react-dom": "^19.2.3",
    "tailwindcss": "^4.1.18",
    "typescript": "5.9.3",
    "vite": "^6.3.5",
    "vite-tsconfig-paths": "^5.1.4",
    "vitest": "^3.0.5",
    "web-vitals": "^4.2.4"
  }
}